package com.payable.app.presentation.offers

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.AccountBalance
import com.payable.app.domain.model.LoanOffer
import com.payable.app.domain.model.OfferType

object OffersMockData {

    val mockOffers = listOf(
        LoanOffer(
            id = 1,
            companyName = "SoFi",
            logoRes = Icons.Default.AccountBalance,
            type = OfferType.LOAN,
            minAmount = 5000,
            maxAmount = 100000,
            minTermMonths = 24,
            maxTermMonths = 84,
            interestRate = 8.99,
            isFastApproval = true,
            colorAccent = 0xFF0066FF,
        ),
        LoanOffer(
            id = 2,
            companyName = "Citi Bank",
            logoRes = Icons.Default.AccountBalance,
            type = OfferType.LOAN,
            minAmount = 2000,
            maxAmount = 50000,
            minTermMonths = 36,
            maxTermMonths = 60,
            interestRate = 7.99,
            colorAccent = 0xFF00C853,
        ),
        LoanOffer(
            id = 3,
            companyName = "Wells Fargo",
            logoRes = Icons.Default.AccountBalance,
            type = OfferType.LOAN,
            minAmount = 3000,
            maxAmount = 400000,
            minTermMonths = 12,
            maxTermMonths = 72,
            interestRate = 6.99,
            colorAccent = 0xFFCC0000,
        ),
        LoanOffer(
            id = 4,
            companyName = "Chase Bank",
            logoRes = Icons.Default.AccountBalance,
            type = OfferType.LOAN,
            minAmount = 10000,
            maxAmount = 300000,
            minTermMonths = 24,
            maxTermMonths = 60,
            interestRate = 9.99,
            colorAccent = 0xFF003366,
        ),
        LoanOffer(
            id = 5,
            companyName = "Bank of America",
            logoRes = Icons.Default.AccountBalance,
            type = OfferType.LOAN,
            minAmount = 5000,
            maxAmount = 200000,
            minTermMonths = 12,
            maxTermMonths = 84,
            interestRate = 10.49,
            colorAccent = 0xFF007FFF,
        ),
        LoanOffer(
            id = 6,
            companyName = "Capital One",
            logoRes = Icons.Default.AccountBalance,
            type = OfferType.LOAN,
            minAmount = 4000,
            maxAmount = 150000,
            minTermMonths = 36,
            maxTermMonths = 60,
            interestRate = 11.99,
            colorAccent = 0xFFFF6600,
        ),
        LoanOffer(
            id = 7,
            companyName = "Discover",
            logoRes = Icons.Default.AccountBalance,
            type = OfferType.LOAN,
            minAmount = 2500,
            maxAmount = 35000,
            minTermMonths = 36,
            maxTermMonths = 84,
            interestRate = 6.99,
            isFastApproval = true,
            colorAccent = 0xFF000000,
        ),
        LoanOffer(
            id = 8,
            companyName = "LendingClub",
            logoRes = Icons.Default.AccountBalance,
            type = OfferType.LOAN,
            minAmount = 1000,
            maxAmount = 40000,
            minTermMonths = 36,
            maxTermMonths = 60,
            interestRate = 5.99,
            colorAccent = 0xFF339966,
        ),
        LoanOffer(
            id = 9,
            companyName = "Upstart",
            logoRes = Icons.Default.AccountBalance,
            type = OfferType.MICROLOAN,
            minAmount = 1000,
            maxAmount = 50000,
            minTermMonths = 36,
            maxTermMonths = 60,
            interestRate = 6.60,
            isFastApproval = true,
            colorAccent = 0xFF00BCD4,
        ),
        LoanOffer(
            id = 10,
            companyName = "Avant",
            logoRes = Icons.Default.AccountBalance,
            type = OfferType.MICROLOAN,
            minAmount = 2000,
            maxAmount = 35000,
            minTermMonths = 9,
            maxTermMonths = 36,
            interestRate = 9.95,
            isFastApproval = true,
            colorAccent = 0xFF4CAF50,
        ),
        LoanOffer(
            id = 11,
            companyName = "LightStream",
            logoRes = Icons.Default.AccountBalance,
            type = OfferType.LOAN,
            minAmount = 5000,
            maxAmount = 100000,
            minTermMonths = 24,
            maxTermMonths = 84,
            interestRate = 6.99,
            colorAccent = 0xFFFFD600,
        ),
        LoanOffer(
            id = 12,
            companyName = "PenFed Credit Union",
            logoRes = Icons.Default.AccountBalance,
            type = OfferType.LOAN,
            minAmount = 600,
            maxAmount = 50000,
            minTermMonths = 12,
            maxTermMonths = 60,
            interestRate = 6.99,
            colorAccent = 0xFF0066CC,
        ),
        LoanOffer(
            id = 13,
            companyName = "Best Egg",
            logoRes = Icons.Default.AccountBalance,
            type = OfferType.MICROLOAN,
            minAmount = 2000,
            maxAmount = 50000,
            minTermMonths = 36,
            maxTermMonths = 60,
            interestRate = 6.99,
            isFastApproval = true,
            colorAccent = 0xFFF75555,
        ),
        LoanOffer(
            id = 14,
            companyName = "Patelco Credit Union",
            logoRes = Icons.Default.AccountBalance,
            type = OfferType.LOAN,
            minAmount = 300,
            maxAmount = 50000,
            minTermMonths = 6,
            maxTermMonths = 60,
            interestRate = 6.99,
            colorAccent = 0xFF2196F3,
        ),
        LoanOffer(
            id = 15,
            companyName = "Ace Cash Express",
            logoRes = Icons.Default.AccountBalance,
            type = OfferType.MICROLOAN,
            minAmount = 100,
            maxAmount = 2000,
            minTermMonths = 0,
            maxTermMonths = 1,
            interestRate = 200.0,
            isFastApproval = true,
            colorAccent = 0xFFFF0000,
        ),
        LoanOffer(
            id = 16,
            companyName = "Check Into Cash",
            logoRes = Icons.Default.AccountBalance,
            type = OfferType.MICROLOAN,
            minAmount = 50,
            maxAmount = 1000,
            minTermMonths = 0,
            maxTermMonths = 1,
            interestRate = 390.0,
            isFastApproval = true,
            colorAccent = 0xFF9C27B0,
        ),
        LoanOffer(
            id = 17,
            companyName = "Speedy Cash",
            logoRes = Icons.Default.AccountBalance,
            type = OfferType.MICROLOAN,
            minAmount = 100,
            maxAmount = 1500,
            minTermMonths = 0,
            maxTermMonths = 1,
            interestRate = 460.0,
            isFastApproval = true,
            colorAccent = 0xFFFF9800,
        ),
        LoanOffer(
            id = 18,
            companyName = "NetCredit",
            logoRes = Icons.Default.AccountBalance,
            type = OfferType.MICROLOAN,
            minAmount = 1000,
            maxAmount = 10000,
            minTermMonths = 1,
            maxTermMonths = 36,
            interestRate = 35.99,
            colorAccent = 0xFF0066CC,
        ),
        LoanOffer(
            id = 19,
            companyName = "OppLoans",
            logoRes = Icons.Default.AccountBalance,
            type = OfferType.MICROLOAN,
            minAmount = 500,
            maxAmount = 4000,
            minTermMonths = 9,
            maxTermMonths = 36,
            interestRate = 160.0,
            isFastApproval = true,
            colorAccent = 0xFF4CAF50,
        ),
        LoanOffer(
            id = 20,
            companyName = "Rise Credit",
            logoRes = Icons.Default.AccountBalance,
            type = OfferType.MICROLOAN,
            minAmount = 300,
            maxAmount = 5000,
            minTermMonths = 4,
            maxTermMonths = 26,
            interestRate = 99.0,
            colorAccent = 0xFF0066FF,
        ),
        LoanOffer(
            id = 21,
            companyName = "LendUp",
            logoRes = Icons.Default.AccountBalance,
            type = OfferType.MICROLOAN,
            minAmount = 100,
            maxAmount = 1000,
            minTermMonths = 0,
            maxTermMonths = 1,
            interestRate = 300.0,
            isFastApproval = true,
            colorAccent = 0xFF8BC34A,
        ),
    )
}


